### ISSUE TITLE
How to insert file?

### ISSUE THREAD

**Issue by Antho85** [consp/vbfdecode#1]
Absolute newb and trying to figure out where i put the VBF file path? Below is my file path to the VBF file i'm trying to decode. Thanks for any help. I have been serching online for awhile and just cant get my head wrapped around it. 

"C:\Users\john\Desktop\vbfdecode-master\MU5T-14H027-EKJ.VBF"

**Comment by consp** [comment]
`python3 vbfdecode.py 'C:\Users\john\Desktop\vbfdecode-master\MU5T-14H027-EKJ.VBF'`

You might need to replace every "\\" with "\\\\". Windows is broken by default and it might work but YMMV, I recommend using linux as that's wat it was written on.

You can run the [WSL](https://docs.microsoft.com/en-us/windows/wsl/install), maybe that will work more easilly.

**Comment by consp** [comment]
Closed for no response and most likely and issue with escape characters or windows backslashes.
